#!/bin/sh
set -eu
OUTPUT_FILE=generated_pages.ts
cd pages
fd html -x echo {.} >z_list
cd ..
printf '// generated by gen-pages.sh
export const pages = { 
' > $OUTPUT_FILE;
while read line; do
  echo processing "pages/$line.html"
  printf "  '$line': \`" >> $OUTPUT_FILE
  cat "pages/$line.html" | sd '\n' '' >> $OUTPUT_FILE
  echo '`,' >> $OUTPUT_FILE
done <pages/z_list

printf '};
// generated by gen-pages.sh
' >> $OUTPUT_FILE;

echo done generating $OUTPUT_FILE
