export const songs = {
  'aa-laut-ke-aja-mere-meet-piano': "Aa Laut Ke Aja Mere Meet",
  'aaja-sanam-madhur-chandni-piano': "Aaja Sanam Madhur Chandni Mein",
  'aane-wala-pal-jane-wala-hai-piano': "Aane Wala Pal Jane Wala Hai",
  'aankh-marey-piano': "Aankh Marey O Ladki Aankh Mare",
  'aapke-pyaar-mein-hum-savarne-lage-piano': "Aapke Pyaar Mein Hum Savarne Lage ",
  'aapki-nazro-ne-samjha-piano': "Aapki Nazro Ne Samjha Pyar Ke Kabil Mujhe",
  'aarti-kunj-bihari-ki-piano': "Aarti Kunj Bihari Ki",
  'achyutam-keshavam-krishna-damodaram-piano': "Achyutam Keshavam Krishna Damodaram",
  'adha-hai-chandrama-piano': "Adha Hai Chandrama Raat Aadhi",
  'ae-dil-hai-mushkil-piano': "Ae Dil Hai Mushkil - Title Track - Tu Safar Mera",
  'ae-watan-humko-teri-kasam-piano': "Ae Watan Ae Watan Humko Teri Kasam",
  'agar-tum-mil-jao-piano': "Agar Tum Mil Jao",
  'aisa-des-hai-mera-piano': "Aisa Des Hai Mera - Dharti Sunehri Ambar Neela",
  'aisi-lagi-lagan-piano': "Aisi Lagi Lagan, Meera Ho Gayi Magan",
  'ajeeb-dastan-hai-yeh-piano': "Ajeeb Dastan Hai Yeh",
  'akele-hain-to-kya-gum-hai-piano': "Akele Hain To Kya Gum Hai",
  'all-i-want-for-christmas-is-you-piano': "All I Want For Christmas Is You",
  'ambe-tu-hai-jagdambe-kali-piano': "Ambe Tu Hai Jagdambe Kali Aarti",
  'ankhiyon-ke-jharokhon-se-piano': "Ankhiyon Ke Jharokhon Se",
  'apni-to-jaise-taise-piano': "Apni To Jaise Taise, Thodi Aise Ya Waise",
  'are-re-are-ye-kya-hua-piano': "Are Re Are Ye Kya Hua - Dil To Pagal Hai",
  'aye-malik-tere-bande-hum-piano': "Aye Malik Tere Bande Hum",
  'aye-mere-humsafar-ek-zara-piano': "Aye Mere Humsafar Ek Zara Intezaar",
  'aye-mere-watan-ke-logo-piano': "Aye Mere Watan Ke Logo - Full Song - Notes Corrected",
  'aye-watan-tere-liye-piano': "Aye Watan Tere Liye - Dil Diya Hai Jaan Bhi Denge",
  'main-agar-kahoon-piano': "Main Agar Kahoon - Tumko Paya Hai To - Keyboard Notes",
  'baa-baa-black-sheep-piano': "Baa Baa Black Sheep. Have You Any Wool?",
  'badan-pe-sitare-lapete-huye-piano': "Badan Pe Sitare Lapete Huye",
  'bade-achhe-lagte-hai-piano': "Bade Achhe Lagte Hai",
  'baharon-phool-barsao-piano': "Baharon Phool Barsao",
  'bahut-pyar-karte-hai-piano': "Bahut Pyar Karte Hai Tumko Sanam",
  'behti-hawa-sa-tha-woh': "Behti Hawa Sa Tha Woh",
  'bekhayali-kabir-singh-piano': "Bekhayali - Kabir Singh (2019)",
  'happy-birthday-to-you-piano': "Birthday Song - Happy Birthday to You",
  'genda-phool-piano': "Genda Phool - Badshah - Boro Loker Beti Lo",
  'hai-preet-jahan-ki-reet-sada-piano': "Hai Preet Jahan Ki Reet Sada - Bharat Ka Rehne Wala Hoon",
  'panghat-roohi-piano': "Panghat - Bahut Kathin Hai Dagar Panghat Ki - Roohi (2021)",
  'chal-akela-chal-akela-piano': "Chal Akela Chal Akela Tera Mela",
  'chalte-chalte-mere-yeh-geet-piano': "Chalte Chalte Mere Yeh Geet",
  'chalte-chalte-yunhi-koi-mil-gaya-tha-piano': "Chalte Chalte Yunhi Koi Mil Gaya Tha – Pakeezah",
  'chalte-chalte-yun-hi-ruk-jaata-piano': "Chalte Chalte Yunhi Ruk Jata Hoon Main",
  'chalti-hai-kya-9-se-12-piano': "Chalti Hai Kya 9 Se 12 - Keyboard Notes",
  'chand-mera-dil-chandni-ho-tum-piano': "Chand Mera Dil Chandni Ho Tum",
  'chand-sifarish-jo-karta-hamari-piano': "Chand Sifarish Jo Karta Hamari",
  'chandi-jaisa-rang-hai-tera-piano': "Chandi Jaisa Rang Hai Tera, Sone Jaise Baal",
  'chhoti-chhoti-gaiya-piano': "Chhoti Chhoti Gaiya Chhote Chhote Gwal ",
  'chookar-mere-man-ko-piano': "Chookar Mere Man Ko, Kiya Tune Kya Isharaa - (Notes Corrected)",
  'christmas-song-jingle-bells-piano': "Christmas Song - Jingle Bells",
  'chura-liya-hai-tumne-jo-dil-ko-piano': "Chura Liya Hai Tumne Jo Dil Ko",
  'sabarmati-ke-sant-piano': "De Di Hame Azadi - Sabarmati Ke Sant",
  'dekhte-dekhte-sochta-hoon-piano': "Dekhte Dekhte - Sochta Hoon ke Woh Kitne Masoom",
  'dhoom-machale-dhoom': "Dhoom Machale Dhoom Machale Dhoom",
  'dil-apna-aur-preet-parai': "Dil Apna Aur Preet Parai",
  'dil-hai-chota-sa': "Dil Hai Chota Sa Choti Si Asha",
  'dil-ke-jharoke-mein-tujko-bithakar-piano': "Dil Ke Jharoke Mein Tujko Bithakar",
  'dil-kya-kare-jab-kisi-se-piano': "Dil Kya Kare Jab Kisi Se",
  'dil-to-pagal-hai-piano': "Dil To Pagal Hai, Dil Deewana Hai",
  'do-dil-mil-rahe-hain-piano': "Do Dil Mil Rahe Hain, Magar Chupke Chupke",
  'do-lafzon-ki-hai-dil-ki-kahani-piano': "Do Lafzon Ki Hai Dil Ki Kahani",
  'ek-din-bik-jayega': "Ek Din Bik Jayega Mati Ke Mol",
  'ek-hasina-thi-ek-diwana-tha-piano': "Ek Haseena Thi Ek Deewana Tha",
  'ek-pardesi-mera-dil': "Ek Pardesi Mera Dil Le Gaya",
  'ek-pyar-ka-nagma-hai-piano': "Ek Pyar ka Nagma Hai",
  'jeeta-tha-jiske-liye-piano': "Jeeta Tha Jiske Liye -  Ek Aisi Ladki Thi",
  'my-heart-will-go-on-piano': "My Heart Will Go On",
  'galiyan-teri-galiyan-piano': "Galiyan Teri Galiyan",
  'gayatri-mantra-piano': "Gayatri Mantra - Om Bhur Bhuvah Swaha",
  'rang-de-tu-mohe-gerua': "Gerua - Rang De Tu Mohe Geruaa",
  'gulabi-aankhen-jo-teri-dekhi-piano': "Gulabi Aankhen Jo Teri Dekhi",
  'hai-apna-dil-to-awara-piano': "Hai Apna Dil To Awara",
  'hamari-adhuri-kahani-piano': "Hamari Adhuri Kahani",
  'hanuman-chalisa-1-piano': "Hanuman Chalisa - Version 1",
  'hanuman-chalisa-2-piano': "Hanuman Chalisa - Version 2",
  'hare-krishna-mantra-dhun-piano': "Hare Krishna Mantra - Hare Krishna, Hare Krishna",
  'hey-ram-hey-ram-piano': "Hey Ram Hey Ram",
  'ho-gaya-hai-tujhko-piano': "Ho Gaya Hai Tujhko To Pyar Sajna – Na Jaane Mere",
  'hothon-se-choo-lo-tum-piano': "Hothon Se Choo Lo Tum",
  'hum-ko-man-ki-shakti-dena-piano': "Hum Ko Man Ki Shakti Dena",
  'itni-shakti-hame-dena-data-piano': "Itni Shakti Hame Dena Data",
  'jaane-kahan-gaye-woh-din': "Jaane Kahan Gaye Woh Din",
  'jab-koi-baat-bigad-jaye-piano': "Jab Koi Baat Bigad Jaye",
  'jag-ghoomeya': "Jag Ghoomeya Thare Jaisa Na Koi",
  'jagat-ke-rang-kya-dekhu-piano': "Jagat Ke Rang Kya Dekhu - Krishna Bhajan",
  'jahan-daal-daal-par-piano': "Jahan Daal Daal Par Sone Ki Chidiya",
  'jai-ganesh-deva-ganesh-aarti-piano': "Jai Ganesh Deva - Ganesh Aarti",
  'jai-ho-aaja-aaja-jind': "Jai Ho - Aaja Aaja Jind Shamiyane Ke Tale",
  'jaise-suraj-ki-garmi-se-piano': "Jaise Suraj Ki Garmi Se Jalte Hue Tan Ko",
  'jana-gana-mana-piano': "Jana Gana Mana - National Anthem",
  'janam-janam-janam-saath-chalna': "Janam Janam Janam Saath Chalna",
  'jara-saamne-to-aao-chaliye-hindi': "ज़रा सामने तो आओ छलिये - Harmonium Notes",
  'jeena-jeena-dehleez-pe': "Jeena Jeena - Dehleez Pe Mere Dil Ki",
  'jeena-yahan-marna-yahan-piano': "Jeena Yahan Marna Yahan, Iske Siva Jaana Kahan",
  'jyot-se-jyot-jagate-chalo-piano': "Jyot Se Jyot Jagate Chalo",
  'kabhi-kabhi-mere-dil-mein-piano': "Kabhi Kabhi Mere Dil Mein Khayal Aata Hai",
  'kabhi-khushi-kabhi-gham': "कभी ख़ुशी कभी ग़म - Harmonium Notes",
  'kahin-door-jab-din-dhal-jaye-piano': "Kahin Door Jab Din Dhal Jaye",
  'kal-ho-na-ho-piano': "Kal Ho Naa Ho - Har Ghadi Badal Rahi Hai",
  'kar-chale-hum-fida-piano': "Kar Chale Hum Fida Jan-o Tan Sathiyon",
  'kar-har-maidan-fateh-piano': "Kar Har Maidan Fateh",
  'kaun-hai-jo-sapno-mein-aaya-piano': "Kaun Hai Jo Sapno Mein Aaya - M. Rafi",
  'kisiki-muskurahato-pe-ho-nisar-piano': "Kisiki Muskurahato Pe Ho Nisar",
  'kuch-kuch-hota-hai': "Kuch Kuch Hota Hai",
  'kya-hua-tera-wada-piano': "Kya Hua Tera Wada, Wo Kasam, Wo Irada",
  'lag-ja-gale-ke-phir-ye-piano': "Lag Ja Gale Ke Phir Ye, Haseen Raat Ho Na Ho",
  'likhe-jo-khat-tujhe-piano': "Likhe Jo Khat Tujhe",
  'madhuban-khushboo-deta-hai-piano': "Madhuban Khushboo Deta Hai",
  'maha-mrityunjaya-mantra-piano': "Maha Mrityunjaya Mantra - Om Tryambakam Yajamahe",
  'main-shayar-to-nahin-piano': "Main Shayar To Nahin",
  'man-dole-mera-tan-dole-piano': "Man Dole Mera Tan Dole",
  'mangal-bhavan-amangal-hari-piano': "Mangal Bhavan Amangal Hari - Ramayan Chaupai",
  'mehndi-laga-ke-rakhna': "Mehndi Laga Ke Rakhna",
  'mera-aapki-kripa-se-piano': "Mera Aapki Kripa Se Sab Kaam Ho Raha Hai",
  'mera-bhola-hai-bhandari-piano': "Mera Bhola Hai Bhandari, Kare Nandi Ki Sawari",
  'mera-dil-ye-pukare-aaja': "Mera Dil Ye Pukare Aaja",
  'mera-naam-raju-piano': "Mera Naam Raju Gharana Anaam - Keyboard Notes",
  'mera-rang-de-basanti-chola-shaheed-piano': "Mera Rang De Basanti Chola - Shaheed",
  'mere-haath-mein-tera-haath': "Mere Haath Mein Tera Haath Ho",
  'mere-rang-me-rangne-wali-piano': "Mere Rang Me Rangne Wali",
  'mere-rashke-qamar-piano': "Mere Rashke Qamar",
  'mere-sapno-ki-rani-piano': "Mere Sapno Ki Rani Kab Aayegi Tu",
  'meri-mehbooba': "Meri Mehbooba - Kisi Roz Tumse Mulakaat Hogi",
  'muskurane-ki-wajah-piano': "Muskurane Ki Wajah Tum Ho",
  'nagin-dhun-piano': "Nagin Dhun - Piano Notes",
  'nand-ke-anand-bhayo-piano': "Nand Ke Anand Bhayo – Janmashtami Bhajan",
  'navkar-namokar-mantra-piano': "Navkar Mantra - Namokar Mantra",
  'o-duniya-ke-rakhwale-hindi': "ओ दुनियाँ के रख वाले - Harmonium Notes",
  'o-mere-dil-ke-chain-piano': "O Mere Dil Ke Chain",
  'o-sathi-re-tere-bina-piano': "O Sathi Re Tere Bina Bhi Kya Jeena",
  'old-macdonald-had-a-farm-piano': "Old MacDonald Had A Farm",
  'om-gan-ganpataye-namo-namah-piano': "Om Gan Ganpataye Namo Namah - Ganesh Mantra",
  'om-jai-jagdish-hare-piano': "Om Jai Jagdish Hare",
  'om-namah-shivay-mantra-piano': "Om Namah Shivay - Har Har Bhole Namah Shiva",
  'pal-pal-dil-ke-paas-piano': "Pal Pal Dil Ke Paas",
  'panchi-banu-udti-phiru': "Panchi Banu Udti Phiru - Keyboard Notes",
  'pardesi-pardesi-jana-nahi-piano': "Pardesi Pardesi Jana Nahi",
  'pehla-nasha-pehla-khumar': "Pehla Nasha Pehla Khumar",
  'phoolon-ke-rang-se-piano': "Phoolon Ke Rang Se, Dil Ki Kalam Se",
  'prem-ratan-dhan-payo': "Prem Ratan Dhan Payo",
  'pukarta-chala-hoon-main-piano': "Pukarta Chala Hoon Main",
  'pyaar-hua-ikraar-hua': "Pyaar Hua Ikraar Hua Hai - Keyboard Notes",
  'pyar-diwana-hota-hai-piano': "Pyar Diwana Hota Hai",
  'raghupati-raghav-raja-ram-piano': "Raghupati Raghav Raja Ram",
  'rahi-manva-dukh-ki-chinta': "Rahi Manva Dukh Ki Chinta",
  'rang-barse-bheege-chunar-wali': "Rang Barse Bheege Chunar Wali",
  'rim-jhim-gire-sawan-piano': "Rim Jhim Gire Sawan",
  'ruk-ja-o-dil-deewane-piano': "Ruk Ja O Dil Deewane",
  'sajan-re-jhoot-mat-bolo-piano': "Sajan Re Jhoot Mat Bolo",
  'sanam-re-sanam-re-piano': "Sanam Re, Sanam Re",
  'sare-jahan-se-achha-piano': "Sare Jahan Se Achha Hindustan Hamara",
  'shape-of-you-piano': "Shape of You - Ed Sheeran",
  'om-jai-shiv-omkara-piano': "Shiv Aarti - Om Jai Shiv Omkara",
  'shiv-shankar-ko-jisne-puja-piano': "Shiv Shankar Ko Jisne Puja",
  'shri-banke-bihari-teri-aarti-piano': "Shri Banke Bihari Teri Aarti Gaun",
  'shri-ramchandra-kripalu-bhajman-piano': "Shri Ramchandra Kripalu Bhajman",
  'shyam-teri-bansi-pukare-radha-naam-piano': "Shyam Teri Bansi Pukare Radha Naam",
  'slow-motion-bharat-piano': "Slow Motion - Bharat",
  'soch-na-sake-piano': "Soch Na Sake - Tere Liye Duniya Chod Di Hai",
  'sooraj-dooba-hai-yaaron': "Sooraj Dooba Hai Yaaron",
  'sukhkarta-dukhharta-piano': "Sukhkarta Dukhharta – Jai Dev Jai Mangal Murti",
  'swag-se-swagat': "Swag Se Swagat - Swag Se Karenge Sabka Swagat",
  'shiv-tandav-stotra-piano': "Shiv Tandav Stotram",
  'tere-jaisa-yaar-kahaa-piano': "Tere Jaisa Yaar Kahaa",
  'tere-man-mein-ram-piano': "Tere Man Mein Ram, Tan Mein Ram",
  'tere-naam-humne-kiya-hai-piano': "Tere Naam Humne Kiya Hai - Tere Naam ",
  'teri-duniya-se-door': "Teri Duniya Se Door Chale Hoke Majboor",
  'tora-man-darpan-kehlaye': "Tora Man Darpan Kehlaye",
  'tu-pyar-ka-sagar-hai-piano': "Tu Pyar Ka Sagar Hai",
  'tujhme-rab-dikhta-hai-piano': "Tujh mein Rab Dikhta Hai - Tu Hi To Jannat Meri",
  'tujhe-dekha-to-ye-jana-sanam-piano': "Tujhe Dekha To Ye Jana Sanam",
  'tujhse-naraz-nahi-zindagi-piano': "Tujhse Naraz Nahi Zindagi",
  'tum-hi-ho-piano': "Tum Hi Ho - Hum Tere Bin Ab Reh Nahi Sakte",
  'tumko-dekha-to-yeh-khayal-aaya-piano': "Tumko Dekha to Yeh Khayal Aaya",
  'twinkle-twinkle-little-star-piano': "Twinkle Twinkle Little Star",
  'we-wish-you-a-merry-christmas-piano': "We Wish You A Merry Christmas",
  'woh-sham-kuchh-ajeeb-thi-piano': "Woh Sham Kuchh Ajeeb Thi",
  'yashomati-maiya-se-bole-nandlala-piano': "Yashomati Maiya Se Bole Nandlala",
  'ye-sama-hai-ye-pyaar-ka-piano': "Ye Sama, Sama Hai Ye Pyaar Ka",
  'ye-sham-mastani-piano': "Ye Sham Mastani Madhosh Kiye Jaye",
  'zindagi-pyar-ka-geet-hai-piano': "Zindagi Pyaar Ka Geet Hai, Isse Har Dil Ko Gaana Padega",
};